version: '3'

services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    image: ct-terraform-aws-lambda:${GIT_COMMIT:-latest}
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - LOCALSTACK_HOST=localstack
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.11.4
    environment:
      - SERVICES=events,iam,logs,lambda,sns,sqs,sts
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGIONc=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/tmp/localstack"

volumes:
  localstack-data:
